COLOR_PALETTE = {};

//salmon orange, 238,110,115
COLOR_PALETTE.PRIMARY_THEME_COLOR_HEX_STRING = '#EE6E73'
//teal green 39,170,158
COLOR_PALETTE.SECONDARY_THEME_COLOR_HEX_STRING = '#27AA9E'
//teal green faded
COLOR_PALETTE.SECONDARY_THEME_COLOR_HEX_STRING_FADED = '#7BACA9'
//soft blue
COLOR_PALETTE.BLUE_THEME_COLOR_HEX_STRING = '#3763B4'
//soft blue faded
COLOR_PALETTE.BLUE_THEME_COLOR_HEX_STRING_FADED = '#748EBA'