sudo: required
language: node_js
before_install:
  - "git submodule update --init --recursive"
node_js:
  - "0.12"
install:
  - "curl https://install.meteor.com | /bin/sh"
  - "npm install -g gagarin"
services:
  - mongodb
script:
  - cd ResourceManager; gagarin -v
notifications:
  slack: ece458:OHYqdH5MDfVDvhvydEcs0Wsm