sudo: required
language: node_js
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "git submodule update --init --recursive"
  - "phantomjs --webdriver=9515 &"
node_js:
  - "0.12"
install:
  - "curl https://install.meteor.com | /bin/sh"
  - "npm install -g gagarin"
services:
  - mongodb
script:
  - cd ResourceManager; gagarin -v
notifications:
  slack: ece458:OHYqdH5MDfVDvhvydEcs0Wsm